### ISSUE TITLE
Cannot build the code generation tools

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/mozc#191]
```
Using the latest version of depot_tools, mozc
python 2.7.3, Win7U sp1 x64

Following https://code.google.com/p/mozc/wiki/WindowsBuildInstructions

python build_mozc.py build_tools -c Release

INFO: Running: cmd.exe /C E:\Project\Archieve\C++\mozc\src\tools\build_ninja.bat

System cannot find the file.
Traceback (most recent call last):
  File "build_mozc.py", line 1462, in <module>
    main()
  File "build_mozc.py", line 1447, in main
    BuildToolsMain(cmd_opts, cmd_args, original_directory_name)
  File "build_mozc.py", line 960, in BuildToolsMain
    BuildNinja()
  File "build_mozc.py", line 944, in BuildNinja
    RunOrDie(['cmd.exe', '/C', build_ninja_bat])
  File "E:\Project\Archieve\C++\mozc\src\build_tools\util.py", line 97, in RunOr
Die
    '==========']))
build_tools.util.RunOrDieError:
==========
 ERROR: cmd.exe /C E:\Project\Archieve\C++\mozc\src\tools\build_ninja.bat
```

Original issue reported on code.google.com by `saberconer@gmail.com` on 7 May 2013 at 2:14

**Comment by yukawa** [comment]
So far I could not reproduce this issue.  Can you try again with the latest version of Mozc and file a new bug if you can still see the same or a similar error?
