### ISSUE TITLE
build error  in terget linux

### ISSUE THREAD

**Issue by lv7777** [google/mozc#396]
I tried build `Release unix/ibus/ibus.gyp:ibus_mozc  server/server.gyp:mozc_server gui/gui.gyp:mozc_tool renderer/renderer.gyp:mozc_renderer`

I occurred error, but i dont understand "what file is lacked?"

please tell me.

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "build_mozc.py", line 1257, in <module>
    main()
  File "build_mozc.py", line 1244, in main
    BuildMain(cmd_opts, cmd_args)
  File "build_mozc.py", line 875, in BuildMain
    BuildWithNinja(options, targets)
  File "build_mozc.py", line 849, in BuildWithNinja
    RunOrDie([ninja, '-C', build_arg] + ninja_targets)
  File "build_tools/util.py", line 92, in RunOrDie
    process = subprocess.Popen(argv)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Uncaught exception. Entering post mortem debugging
```

**Comment by yukawa** [comment]
Can you check if the following command succeeds or not?

```sh
ninja --version
```

If it doesn't success, it's probably [ninja](https://github.com/ninja-build/ninja) that your environment missed.

**Comment by lv7777** [comment]
I don't have ninja and `apt-get install ninja`,so I moved on next step! thanks!

but build was looped. 
Is this behave build success?

```
INFO: Running: ninja -C out_linux/Release ibus_mozc mozc_emacs_helper mozc_server mozc_tool mozc_renderer
log: ninja version 0.1.3 initializing
log: magic group: gid=0 (root)
log: entering main loop
log: generating initial pid array..
log: now monitoring process activity
```

and out_linux/Release is existed obj/ dir and many *.ninja files.

**Comment by lv7777** [comment]
I am writing this to inform you that the problem is now solved. Thank you for your help.

`apt-get install ninja-build`

**Comment by yukawa** [comment]
Thank you for your update.  Seems that no further action is needed on Mozc upstream side and we can close this thread.
