### ISSUE TITLE
building executables error

### ISSUE THREAD

**Issue by basebol** [google/mozc#457]
how do you find the mac sdk
```
/Users/basebol/mozc/src/mac/Japanese.lproj/Config.xib:global: error: Compiling for earlier than macOS 10.6 is no longer supported. [12]
[172/821] MACTOOL copy-bundle-resource ...Palette/English.lproj/InfoPlist.string
FAILED: CharacterPalette.app/Contents/Resources/English.lproj/InfoPlist.strings 
 ./gyp-mac-tool copy-bundle-resource ../../data/mac/CharacterPalette/English.lproj/InfoPlist.strings CharacterPalette.app/Contents/Resources/English.lproj/InfoPlist.strings False
Traceback (most recent call last):
  File "./gyp-mac-tool", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "./gyp-mac-tool", line 28, in main
    exit_code = executor.Dispatch(args)
  File "./gyp-mac-tool", line 43, in Dispatch
    return getattr(self, method)(*args[1:])
  File "./gyp-mac-tool", line 66, in ExecCopyBundleResource
    self._CopyStringsFile(source, dest, convert_to_binary)
  File "./gyp-mac-tool", line 109, in _CopyStringsFile
    import CoreFoundation
ImportError: No module named CoreFoundation
[177/821] CXX obj.host/third_party/prot...iler/java/protoc.java_primitive_field.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "build_mozc.py", line 1366, in <module>
    main()
  File "build_mozc.py", line 1362, in main
    procedure[1](cmd_opts, cmd_args, original_directory_name)
  File "build_mozc.py", line 988, in BuildMain
    BuildWithNinja(options, targets, original_directory_name)
  File "build_mozc.py", line 960, in BuildWithNinja
    RunOrDie([make_command] + build_args + target_names)
  File "/Users/basebol/mozc/src/build_tools/util.py", line 99, in RunOrDie
    '==========']))
build_tools.util.RunOrDieError: 
```

**Comment by basebol** [comment]
same error as https://github.com/google/mozc/issues/430

**Comment by basebol** [comment]
My mac doesn't have an high enough sdk.
