### ISSUE TITLE
jnitestingbackdoor cannot be built.

### ISSUE THREAD

**Issue by justoneplanet** [google/mozc#473]
### Reproduce

Execute the following commands.

```bash
python build_mozc.py clean
python build_mozc.py gyp --target_platform=Android --android_arch=arm --android_application_id=info.justoneplanet.android.inputmethod.japanese
python build_mozc.py build android/android.gyp:jnitestingbackdoor -c Debug
```

### Expected

```txt
INFO: Generating version definition file...
INFO: Version string is 2.23.2815.103
INFO: Running: /usr/bin/python /home/mozc_builder/work/mozc/src/build_tools/ensure_gyp_module_path.py --expected=/home/mozc_builder/work/mozc/src/third_party/gyp/pylib/gyp
INFO: Building GYP command line...
INFO: Android home is set from ANDROID_HOME: /home/mozc_builder/work/android-sdk-linux
INFO: Android NDK home is set from PATH: /home/mozc_builder/work/android-ndk-r16b
INFO: Running GYP...
INFO: Running: /usr/bin/python /home/mozc_builder/work/mozc/src/third_party/gyp/gyp_main.py --depth=. --include=./gyp/common.gypi -D abs_depth=/home/mozc_builder/work/mozc/src -D ext_third_party_dir=/home/mozc_builder/work/mozc/src/third_party -D python_executable=/usr/bin/python ./android/android.gyp ./android/genproto_java.gyp ./android/resources/resources.gyp ./android/userfeedback/userfeedback.gyp ./base/base.gyp ./base/base_test.gyp ./client/client.gyp ./client/client_test.gyp ./composer/composer.gyp ./composer/composer_test.gyp ./config/config.gyp ./config/config_test.gyp ./converter/converter.gyp ./converter/converter_base.gyp ./converter/converter_main.gyp ./converter/converter_test.gyp ./data/test/session/scenario/scenario.gyp ./data/test/session/scenario/usage_stats/usage_stats.gyp ./data_manager/chromeos/chromeos_data_manager.gyp ./data_manager/chromeos/chromeos_data_manager_base.gyp ./data_manager/chromeos/chromeos_data_manager_test.gyp ./data_manager/data_manager.gyp ./data_manager/data_manager_base.gyp ./data_manager/data_manager_test.gyp ./data_manager/oss/oss_data_manager.gyp ./data_manager/oss/oss_data_manager_base.gyp ./data_manager/oss/oss_data_manager_test.gyp ./data_manager/testing/mock_data_manager.gyp ./data_manager/testing/mock_data_manager_base.gyp ./data_manager/testing/mock_data_manager_test.gyp ./dictionary/dictionary.gyp ./dictionary/dictionary_base.gyp ./dictionary/dictionary_test.gyp ./dictionary/file/dictionary_file.gyp ./dictionary/file/dictionary_file_test.gyp ./dictionary/system/system_dictionary.gyp ./dictionary/system/system_dictionary_test.gyp ./engine/engine.gyp ./engine/engine_test.gyp ./gui/gui.gyp ./gyp/tests.gyp ./handwriting/handwriting.gyp ./handwriting/handwriting_test.gyp ./handwriting/zinnia.gyp ./ipc/ipc.gyp ./mac/mac.gyp ./net/jsoncpp.gyp ./net/net.gyp ./net/net_test.gyp ./prediction/prediction.gyp ./prediction/prediction_base.gyp ./prediction/prediction_test.gyp ./protobuf/protobuf.gyp ./protocol/protocol.gyp ./renderer/renderer.gyp ./request/request.gyp ./rewriter/calculator/calculator.gyp ./rewriter/rewriter.gyp ./rewriter/rewriter_base.gyp ./rewriter/rewriter_test.gyp ./server/server.gyp ./session/session.gyp ./session/session_base.gyp ./session/session_test.gyp ./storage/storage.gyp ./storage/storage_test.gyp ./testing/testing.gyp ./transliteration/transliteration.gyp ./transliteration/transliteration_test.gyp ./usage_stats/usage_stats.gyp ./usage_stats/usage_stats_base.gyp ./usage_stats/usage_stats_test.gyp -D branding=Mozc -D use_qt=NO -D qt_dir= -D use_wix=NO -D android_home=/home/mozc_builder/work/android-sdk-linux -D android_arch=arm -D android_ndk_home=/home/mozc_builder/work/android-ndk-r16b -D android_application_id=info.justoneplanet.android.inputmethod.japanese -D android_hide_icon=0 -D android_release_icon=0 -D build_base=/home/mozc_builder/work/mozc/src/out_android -D build_short_base=out_android -D warn_as_error=0 -D channel_dev=1 -D enable_cloud_handwriting=0 -D target_platform=Android --generator-output=. -G output_dir=out_android
INFO: Done
mozc_builder@a09ee1f20851:~/work/mozc/src$ python build_mozc.py build android/android.gyp:jnitestingbackdoor -c Debug
INFO: Running: ninja -C out_android/Debug jnitestingbackdoor
ninja: Entering directory `out_android/Debug'
[46/46] SOLINK /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so
```

### Actual

```txt
FAILED: /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so.TOC 
if [ ! -e /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so -o ! -e /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so.TOC ]; then /home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/arm-linux-androideabi-clang++ -shared -llog -static-libstdc++ -march=armv7-a -o /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so -Wl,-soname=libjnitestingbackdoor.so @/home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so.rsp && { /home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/arm-linux-androideabi-readelf -d /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so | grep SONAME ; /home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/arm-linux-androideabi-nm -gD -f p /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so | cut -f1-2 -d' '; } > /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so.TOC; else /home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/arm-linux-androideabi-clang++ -shared -llog -static-libstdc++ -march=armv7-a -o /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so -Wl,-soname=libjnitestingbackdoor.so @/home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so.rsp && { /home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/arm-linux-androideabi-readelf -d /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so | grep SONAME ; /home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/arm-linux-androideabi-nm -gD -f p /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so | cut -f1-2 -d' '; } > /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so.tmp && if ! cmp -s /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so.tmp /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so.TOC; then mv /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so.tmp /home/mozc_builder/work/mozc/src/android/tests/libs/armeabi-v7a/libjnitestingbackdoor.so.TOC ; fi; fi
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase.a(obj/base/base.cpu_stats.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase.a(obj/base/base.cpu_stats.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase.a(obj/base/base.scheduler.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase.a(obj/base/base.scheduler.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase.a(obj/base/base.unnamed_event.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/net/libhttp_client.a(obj/net/http_client.http_client.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/net/libhttp_client.a(obj/net/http_client.http_client.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/net/libhttp_client.a(obj/net/http_client.http_client.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/net/libhttp_client.a(obj/net/http_client.http_client.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/net/libhttp_client.a(obj/net/http_client.http_client.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/net/libhttp_client.a(obj/net/http_client.proxy_manager.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/net/libhttp_client.a(obj/net/http_client.proxy_manager.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/net/libhttp_client.a(obj/net/http_client.proxy_manager.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/net/libhttp_client.a(obj/net/http_client.proxy_manager.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/net/libhttp_client.a(obj/net/http_client.proxy_manager.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_stream.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.file_util.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.init_mozc.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.init_mozc.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.logging.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.logging.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.logging.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.logging.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.logging.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.logging.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.logging.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.mmap.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.mmap.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.number_util.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.number_util.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.number_util.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.thread.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.util.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.android_util.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libbase_core.a(obj/base/base_core.android_util.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libclock.a(obj/base/clock.clock.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libflags.a(obj/base/flags.flags.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libflags.a(obj/base/flags.flags.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libflags.a(obj/base/flags.flags.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
/home/mozc_builder/work/mozc/src/out_android/mozc_build_tools/ndk-standalone-toolchain/arm/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: obj/base/libflags.a(obj/base/flags.flags.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC
clang50++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "build_mozc.py", line 1236, in <module>
    main()
  File "build_mozc.py", line 1223, in main
    BuildMain(cmd_opts, cmd_args)
  File "build_mozc.py", line 854, in BuildMain
    BuildWithNinja(options, targets)
  File "build_mozc.py", line 828, in BuildWithNinja
    RunOrDie([ninja, '-C', build_arg] + ninja_targets)
  File "/home/mozc_builder/work/mozc/src/build_tools/util.py", line 99, in RunOrDie
    '==========']))
build_tools.util.RunOrDieError: 
==========
 ERROR: ninja -C out_android/Debug jnitestingbackdoor
==========
```

### Patch

It seems that the following patch makes it possible.😇

```txt
diff --git a/src/gyp/common.gypi b/src/gyp/common.gypi
index 6c50e3cb..b175b5fa 100644
--- a/src/gyp/common.gypi
+++ b/src/gyp/common.gypi
@@ -302,6 +302,7 @@
                   # unless we ship a standalone native executable.
                   # See crbug.com/373219.
                   '-fPIE',
+                  '-fPIC',
                 ],
                 'ldflags!': [  # Remove all libraries for GNU/Linux.
                   '<@(linux_ldflags)',
```

**Comment by hiroyuki-komatsu** [comment]
Since the build system for Android library has been changed to Bazel, and CIs for Android was resumed.
Please let us close this issue as obsolete.

Thanks,
