### ISSUE TITLE
Incompatibility with GCC11

### ISSUE THREAD

**Issue by Nocifer** [google/mozc#508]
Hello, I tried to build Mozc from source and I hit the following error:

```
[110/806] ACTION(host) Generating gen/dictionary/pos_matcher.h
[111/806] CXX obj/third_party/abseil-cpp/absl/synchronization/internal/absl_synchronization.graphcycles.o
FAILED: obj/third_party/abseil-cpp/absl/synchronization/internal/absl_synchronization.graphcycles.o 
/usr/bin/clang++ -MMD -MF obj/third_party/abseil-cpp/absl/synchronization/internal/absl_synchronization.graphcycles.o.d -DOS_LINUX -DMOZC_BUILD -DCHANNEL_DEV -DENABLE_GTK_RENDERER -DNDEBUG -DQT_NO_DEBUG -DMOZC_NO_LOGGING -DIGNORE_HELP_FLAG -DIGNORE_INVALID_FLAG -I/build/mozc-ut-common/src/mozc-ut-common-git/src -Igen -I../../third_party/abseil-cpp -fmessage-length=0 -fno-strict-aliasing -funsigned-char -pipe -pthread -fno-omit-frame-pointer -fstack-protector --param=ssp-buffer-size=4 -Wall -Wno-char-subscripts -Wno-sign-compare -Wno-deprecated-declarations -Wwrite-strings -Wno-unknown-warning-option -Wno-inconsistent-missing-override -fPIC -fno-exceptions -Wtype-limits -O2 -D_FORTIFY_SOURCE=2 -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -Wno-deprecated  -Wno-covered-switch-default -Wno-unnamed-type-template-args -Wno-c++11-narrowing -std=c++17  -c ../../third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc -o obj/third_party/abseil-cpp/absl/synchronization/internal/absl_synchronization.graphcycles.o
../../third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:26: error: no member named 'numeric_limits' in namespace 'std'
  if (x->version == std::numeric_limits<uint32_t>::max()) {
                    ~~~~~^
../../third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:41: error: unexpected type name 'uint32_t': expected expression
  if (x->version == std::numeric_limits<uint32_t>::max()) {
                                        ^
../../third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:52: error: no member named 'max' in the global namespace
  if (x->version == std::numeric_limits<uint32_t>::max()) {
                                                 ~~^
3 errors generated.
[111/806] ...
...
...
[124/806] CXX obj.host/third_party/protobuf/src/google/protobuf/protobuf.descriptor.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/build/mozc-ut-common/src/mozc-ut-common-git/src/build_mozc.py", line 889, in <module>
    sys.exit(main())
  File "/build/mozc-ut-common/src/mozc-ut-common-git/src/build_mozc.py", line 874, in main
    BuildMain(cmd_opts, cmd_args)
  File "/build/mozc-ut-common/src/mozc-ut-common-git/src/build_mozc.py", line 614, in BuildMain
    BuildWithNinja(options, targets)
  File "/build/mozc-ut-common/src/mozc-ut-common-git/src/build_mozc.py", line 588, in BuildWithNinja
    RunOrDie([ninja, '-C', build_arg, target_name])
  File "/build/mozc-ut-common/src/mozc-ut-common-git/src/build_tools/util.py", line 96, in RunOrDie
    raise RunOrDieError('\n'.join(['',
build_tools.util.RunOrDieError: 
==========
 ERROR: ninja -C out_linux/Release mozc_server
==========
==> ERROR: A failure occurred in build().
    Aborting...
```

I'm on Arch Linux and I've already been bit once after the upgrade to the new GCC11 and its stricter c++17 configuration, so I downgraded to GCC10 and tried to build again. This time the build almost succeeded but it failed at the linking stage, with:

```
[806/806] LINK mozc_server
INFO: Running: ninja -C out_linux/Release mozc_tool
ninja: Entering directory `out_linux/Release'
[12/154] RULE Generating UI header files from word_register_dialog/word_register_dialog.ui
FAILED: gen/gui/word_register_dialog/ui_word_register_dialog.h 
cd ../../gui; /usr/bin/uic -o "../out_linux/Release/gen/gui/word_register_dialog/ui_word_register_dialog.h" "word_register_dialog/word_register_dialog.ui"
/usr/bin/uic: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libQt5Core.so.5)
/usr/bin/uic: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /usr/lib/libQt5Core.so.5)
[13/154] RULE Generating UI header files from set_default_dialog/set_default_dialog.ui
FAILED: gen/gui/set_default_dialog/ui_set_default_dialog.h 
cd ../../gui; /usr/bin/uic -o "../out_linux/Release/gen/gui/set_default_dialog/ui_set_default_dialog.h" "set_default_dialog/set_default_dialog.ui"
/usr/bin/uic: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libQt5Core.so.5)
/usr/bin/uic: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /usr/lib/libQt5Core.so.5)
[14/154] RULE Generating UI header files from post_install_dialog/post_install_dialog.ui
FAILED: gen/gui/post_install_dialog/ui_post_install_dialog.h 
cd ../../gui; /usr/bin/uic -o "../out_linux/Release/gen/gui/post_install_dialog/ui_post_install_dialog.h" "post_install_dialog/post_install_dialog.ui"
/usr/bin/uic: /usr/lib/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/libQt5Core.so.5)
/usr/bin/uic: /usr/lib/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /usr/lib/libQt5Core.so.5)
[25/154] RULE(host) Generating C++ code from window_info.proto
ninja: build stopped: subcommand failed.
```

I then downgraded libQt5Core.so.5 to a version built against GCC10, tried again to build with GCC10 and this time Mozc built successfully.

Normally I'd be happy to just use GCC10 for the time being and call it a day, but unfortunately due to the Qt5 dependency it quickly becomes kind of a mess, so GCC11 support would be greatly appreciated.

**EDIT:** Forgot to mention, this is probably more of an issue with abseil-cpp rather than with Mozc itself, but I chose to report it here because I noticed that you use an LTS version of abseil-cpp from September 2020, so even if abseil-cpp implements GCC11 support and releases a new version, it may still require special attention on your part to make Mozc compatible with that new version.

**EDIT 2:** I just found out that this has already been reported a few days ago and there is already a third-party fix available, so I'm closing this issue.

**Comment by hiroyuki-komatsu** [comment]
As the reporter mentioned it's duplicate with https://github.com/google/mozc/issues/506
